name: Run PowerShell Script

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run PowerShell script
      run: |
        ./hello-world.ps1
